```{r}
#| label: datasets
```

<!-- This is a reduced table from /etc/Secondary Databases.md -->


| Index | Database                                                                                                                       | Stim. Type                    | Stim. Dur.                                  | Stim. N                                          | Feature N.                                                                 | Ppt. N                        | Feature Source                                        | In studies                                                                                                               |
| ----- | ------------------------------------------------------------------------------------------------------------------------------ | ----------------------------- | ------------------------------------------- | ------------------------------------------------ | -------------------------------------------------------------------------- | ----------------------------- | ----------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------ |
| 1     | [**MediaEval**](https://cvml.unige.ch/databases/emoMusic/)                                                                     | Western pop of various genres | 45                                          | 744                                              | 6669                                                                       | 10/track                      | OpenSMILE                                             | @bai2016di, @bai2017mu, @yang2021an, @chin2018pr, @coutinho2017sh, @markov2014mu, @medina2020em, @wang2022co, @xie2020mu |
| 2     | [**DEAM**](https://cvml.unige.ch/databases/DEAM/)                                                                              | Pop                           | 58 full-length and 1744 45-second excerpts  | 1802                                             | 260                                                                        | 5-10/track                    | OpenSMILE                                             | @sorussa2020em, @orjesek2022en, @panwar2019ar, @zhang2023mo                                                              |
| 3     | [**AMG1608**](https://github.com/loichan-tw/AMG1608_release)                                                                   | Pop                           | 30                                          | 1608                                             | 72                                                                         | 643 MTurk, 22 Taiwan subjects | MIRToolbox, YAAFE                                     | @chen2017co, @hu2017cr, @wang2022cr                                                                                      |
| 4     | [**EMOPIA**](https://annahung31.github.io/EMOPIA/)                                                                             | Piano Solo (pop music)        | 30 to 40                                    | 387                                              | 24                                                                         | 1 annotation/track            | MIDI Toolbox                                          | @bhuvanakumar2023em                                                                                                      |
| 5     | [**NTUMIR**](https://web.archive.org/web/20170510081611/mac.citi.sinica.edu.tw/~yang/MER/NTUMIR-60)                            | Famous pop songs              | 25                                          | 60                                               | 46                                                                         | 40 annotations/track.         | MIRToolbox, Sound Description Toolbox, MA Toolbox     | @chin2018pr                                                                                                              |
| 6     | [**Soundtracks**](https://osf.io/p6vkg/wiki/home/)                                                                             | Obscure film soundtracks      | 15                                          | 110                                              | NA                                                                         | 116 university students       | NA                                                    | @wang2022co                                                                                                              |
| 7     | [**PSIC3839**](https://github.com/xl2218066/PSIC3839)                                                                          | Chinese popular               | full? 180 s excerpts extracted for analyses | 3839                                             | NA                                                                         | 87                            | Librosa                                               | @xu2021us                                                                                                                |
| 8     | [**CH818**](ccmir.cite.hku.hk/data/)                                                                                           | Chinese pop                   | 30                                          | 818                                              | 15                                                                         | 3                             | MIRToolbox, PsySound, ChromaToolbox,Tempogram Toolbox | @hu2017cr                                                                                                                |
| 9     | [**Zhang et al. (2015)**](LINK)                                                                                                | Chinese pop                   | 30                                          | 171                                              | 84 dimensions                                                              | 10                            | MAToolbox, MIRToolbox, Coversongs                     | @zhang2016br                                                                                                             |
| 10    | [**PMEmo**](http://huisblog.cn/PMEmo/)                                                                                         | Choruses of top pop songs     | variable                                    | 794                                              | 6373 static; 260 acoustic low-level features                               | 457                           | ComParE 2013 baseline feature set                     | @zhang2023mo                                                                                                             |
| 11    | [**NJU-V1**](https://cs.nju.edu.cn/sufeng/data/musicmood.htm)                                                                  | Music clips (limited detail)  | variable                                    | 777                                              | Not reported                                                               | NA (lastfm tags)              | NA                                                    | @agarwal2021an                                                                                                           |
| 12    | [**ISMIR-2012**](http://yadingsong.blogspot.com/2015/03/popular-music-emotion-dataset-ismir2012.html)                          | Popular music                 | 30 or 60                                    | 2904                                             | 54                                                                         | NA (lastfm tags)              | MIRToolbox                                            | @agarwal2021an                                                                                                           |
| 13    | [**Spotify API**](https://developer.spotify.com/documentation/web-api)                                                         | Various                       | Variable                                    | 5192 used in @alvarez2023ri                      | 12                                                                         | NA                            | EchoNest                                              | @alvarez2023ri                                                                                                           |
| 14    | [**Acoustic Brainz**](https://acousticbrainz.org/)                                                                             | Various                       | Variable                                    | 60,000 used in @alvarez2023ri                    | Not reported                                                               | NA (lastfm tags)              | Essentia                                              | @alvarez2023ri                                                                                                           |
| 15    | [**MIREX2009**](https://www.music-ir.org/mirex/wiki/2009:Music_Structure_Segmentation_Results)                                 | Popular                       | Full?                                       | 297                                              | 3                                                                          | NA                            | Paulus & Klapuri (2009)                               | @yeh2014po                                                                                                               |
| 16    | [**Million Songs Dataset**](http://millionsongdataset.com/pages/getting-dataset/)                                              | Pop                           | Full                                        | 1,000,000                                        | 55                                                                         | None                          | EchoNest                                              | @cao2023th                                                                                                               |
| 17    | [**Free Music Archive**](https://freemusicarchive.org/home)                                                                    | Various                       | Variable                                    | >100,000                                         | NA                                                                         | NA                            | NA                                                    | @koh2023me                                                                                                               |
| 18    | [**Jamendo**](https://www.music-ir.org/mirex/wiki/2015:Main_Page) | Various                       | Variable                                    | 10,000                                           | 24                                                                         | NA                            | Metadata                                              | @hu2022de                                                                                                                |
| 19    | **Chinese Classical Music Dataset**                                                                                            | Chinese classical             | ~30s                                        | 500                                              | 557                                                                        | 20                            | Essentia, MIRToolbox                                  | @wang2022co                                                                                                              |
