---
title             : "Datasets"
figsintext        : yes
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : no
mask              : no
csl: apa7.csl
#class             : "man"
#output            : papaja::apa6_pdf
bibliography      : references.bib
---

The most frequently used 3 datasets are MediaEval [@soleymani2013], DEAM [@aljanaki2017developing], and AMG1608 [@chen2015amg1608]. These datasets represent Western pop music, are moderate in terms of the size (containing from 744 to 1802 music excerpts) and have been manually annotated by relative large number of participants (either by experts, students, or crowdsourced workers). Two of the most popular datasets offer a large number (260 to 6669) features extracted with OpenSMILE [@eyben2010opensmile]. Looking at the datasets more broadly, the diversity in the size and the features of the datasets is notable. Only two feature extraction tools are used across multiple datasets (OpenSMILE @eyben2010opensmile and MIR Toolbox, @lartillot2007matlab). However, despite this diversity, there does not seem to be a direct link between the model success rates and the features themselves, or at least separating the features from variation created by the dataset size, annotation accuracy and genre is not possible. 

<!-- This is a reduced table from /etc/Secondary Databases.md -->

| Dataset                                                                                                | Stim. Type                 | Stim. Dur. (s)  | Stim. N          | Feature N    | Ppt. N          | Feature Source                                        | In studies                                                                                                               |
| ------------------------------------------------------------------------------------------------------ | -------------------------- | --------------- | ---------------- | ------------ | --------------- | ----------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------ |
| [**MediaEval**](https://cvml.unige.ch/databases/emoMusic/)                                             | Western pop                | 45              | 744              | 6669         | 10/track        | OpenSMILE                                             | @bai2016di, @bai2017mu, @yang2021an, @chin2018pr, @coutinho2017sh, @markov2014mu, @medina2020em, @wang2022co, @xie2020mu |
| [**DEAM**](https://cvml.unige.ch/databases/DEAM/)                                                      | Pop                        | 45              | 1802             | 260          | 5-10/track      | OpenSMILE                                             | @sorussa2020em, @orjesek2022en, @panwar2019ar, @zhang2023mo                                                              |
| [**AMG1608**](https://github.com/loichan-tw/AMG1608_release)                                           | Pop                        | 30              | 1608             | 72           | 643             | MIR Toolbox, YAAFE                                     | @chen2017co, @hu2017cr, @wang2022cr                                                                                      |
| [**EMOPIA**](https://annahung31.github.io/EMOPIA/)                                                     | Piano Solo (pop music)     | 30-40           | 387              | 24           | 1 annot./track  | MIDI Toolbox                                          | @bhuvanakumar2023em                                                                                                      |
| [**NTUMIR**](https://web.archive.org/web/20170510081611/mac.citi.sinica.edu.tw/~yang/MER/NTUMIR-60)    | Famous pop songs           | 25              | 60               | 46           | 40 annot./track | MIR Toolbox, Sound Description Toolbox, MA Toolbox     | @chin2018pr                                                                                                              |
| [**Soundtracks**](https://osf.io/p6vkg/wiki/home/)                                                     | Obscure film soundtracks   | 15              | 110              | NA           | 116             | NA                                                    | @wang2022co                                                                                                              |
| [**PSIC3839**](https://github.com/xl2218066/PSIC3839)                                                  | Chinese popular            | 180             | 3839             | NA           | 87              | Librosa                                               | @xu2021us                                                                                                                |
| [**CH818**](ccmir.cite.hku.hk/data/)                                                                   | Chinese pop                | 30              | 818              | 15           | 3               | MIR Toolbox, PsySound, Chroma Toolbox, Tempogram Toolbox| @hu2017cr                                                                                                                |
| [**Zhang et al. (2015)**](LINK)                                                                        | Chinese pop                | 30              | 171              | 84           | 10              | MA Toolbox, MIR Toolbox, Coversongs                     | @zhang2016br                                                                                                             |
| [**PMEmo**](http://huisblog.cn/PMEmo/)                                                                 | Pop songs                  | Variable        | 794              | 6373         | 457             | ComParE 2013 baseline feature set                     | @zhang2023mo                                                                                                             |
| [**NJU-V1**](https://cs.nju.edu.cn/sufeng/data/musicmood.htm)                                          | Limited detail             | Variable        | 777              | Not reported | NA (tags)       | NA                                                    | @agarwal2021an                                                                                                           |
| [**ISMIR-2012**](http://yadingsong.blogspot.com/2015/03/popular-music-emotion-dataset-ismir2012.html)  | Popular music              | 30 or 60        | 2904             | 54           | NA (tags)       | MIR Toolbox                                            | @agarwal2021an                                                                                                           |
| [**MIREX2009**](https://www.music-ir.org/mirex/wiki/2009:Music_Structure_Segmentation_Results)         | Popular                    | Full            | 297              | 3            | NA              | Paulus & Klapuri (2009)                               | @yeh2014po                                                                                                               |
| [**Million Songs Dataset**](http://millionsongdataset.com/pages/getting-dataset/)                      | Pop                        | Full            | 1,000,000        | 55           | None            | EchoNest                                              | @cao2023th                                                                                                               |
| [**Free Music Archive**](https://freemusicarchive.org/home)                                            | Various                    | Variable        | >100,000         | NA           | NA              | NA                                                    | @koh2023me                                                                                                               |
| [**Jamendo**](https://www.music-ir.org/mirex/wiki/2015:Main_Page)                                      | Various                    | Variable        | 10,000           | 24           | NA              | Metadata                                              | @hu2022de                                                                                                                |
| **Chinese Classical Music Dataset**                                                                    | Chinese classical          | ~30s            | 500              | 557          | 20              | Essentia, MIR Toolbox                                  | @wang2022co                                                                                                              |
Notes: $\dagger$ Used in @alvarez2023ri

<!-- I TOOK THESE OUT FOR NOW
| [**Spotify API**](https://developer.spotify.com/documentation/web-api)                                 | Various                    | Variable        | 5192$\dagger$    | 12           | NA              | EchoNest                                              | @alvarez2023ri                                                                                                           |
| [**Acoustic Brainz**](https://acousticbrainz.org/)                                                     | Various                    | Variable        | 60,000$\dagger$  | Not reported | NA (tags)       | Essentia                                              | @alvarez2023ri                                                                                                           |
-->
